[package]
name = "geo_points"
version = "0.1.0"
edition = "2021"

[dependencies]
geo-types = "0.7.13"
rand = "0.8"
geo = "0.28.0"
image = "0.25.2"
chrono = "0.4.38"
serde_json = "1.0.124"
serde = { version = "1.0.207", features = ["derive"] }
